/**
 * Les 25 objectifs de la quête « 25 choses à faire avant mes 25 ans ».
 *
 * Ces données servent de démonstration *et* de jeu de test pour le moteur
 * d'intelligence : elles couvrent volontairement tous les cas de figure
 * (verrou d'âge, budget hors de portée, dépendance entre objectifs,
 * saisonnalité, objectif presque terminé, objectif final).
 *
 * `monthsFromNow` positionne la date cible relativement à la date d'exécution
 * du seed : le jeu de données ne périme donc jamais.
 */

export type SeedStep = {
  title: string;
  description?: string;
  done?: boolean;
  /** Jours à partir d'aujourd'hui (négatif = passé) */
  dueInDays?: number;
  estimatedMinutes?: number;
  priority?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  children?: SeedStep[];
};

export type SeedGoal = {
  slug: string;
  title: string;
  emoji: string;
  description: string;
  motivation?: string;
  notes?: string;
  category: string;
  color: string;
  status: "TODO" | "IN_PROGRESS" | "WAITING" | "BLOCKED" | "DONE";
  priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  difficulty: number;
  estimatedCost?: number;
  savedAmount?: number;
  estimatedHours?: number;
  monthsFromNow?: number;
  country?: string;
  city?: string;
  minAge?: number;
  people?: string[];
  isFinal?: boolean;
  isFavorit?: boolean;
  dependsOn?: string[];
  steps?: SeedStep[];
  checklist?: string[];
};

export const SEED_GOALS: SeedGoal[] = [
  {
    slug: "camp-boxe-thai-thailande",
    title: "Camp de boxe thaï en Thaïlande",
    emoji: "🥊",
    description:
      "Partir un mois dans un camp de Muay Thaï authentique à Chiang Mai : deux entraînements par jour, vie sur place avec les combattants.",
    motivation: "Savoir jusqu'où mon corps peut aller quand plus personne ne me regarde.",
    category: "sport",
    color: "blush",
    status: "IN_PROGRESS",
    priority: "HIGH",
    difficulty: 4,
    estimatedCost: 2800,
    savedAmount: 950,
    estimatedHours: 320,
    monthsFromNow: 16,
    country: "Thaïlande",
    city: "Chiang Mai",
    minAge: 18,
    steps: [
      {
        title: "Choisir le camp",
        done: true,
        children: [
          { title: "Comparer 5 camps (prix, réputation, hébergement)", done: true },
          { title: "Lire les avis d'anciens élèves francophones", done: true },
          { title: "Contacter le camp retenu par e-mail", done: true },
        ],
      },
      {
        title: "Se mettre au niveau physiquement",
        done: false,
        estimatedMinutes: 60,
        priority: "HIGH",
        children: [
          { title: "3 séances de boxe par semaine pendant 6 mois", done: false },
          { title: "Course à pied 5 km en moins de 25 min", done: true },
          { title: "Renforcement tibias et clinch", done: false },
        ],
      },
      { title: "Atteindre 2 800 € d'épargne", dueInDays: 420, priority: "HIGH" },
      { title: "Vaccins et assurance voyage", dueInDays: 400 },
      { title: "Réserver le vol", dueInDays: 440, priority: "CRITICAL" },
    ],
    checklist: ["Gants 10 oz", "Protège-tibias", "Passeport valide 6 mois", "Visa touriste 30 jours"],
  },
  {
    slug: "camp-kung-fu-chine",
    title: "Camp de kung-fu en Chine",
    emoji: "🐉",
    description:
      "Trois semaines dans une académie traditionnelle près des monts Song, discipline quotidienne à la Shaolin.",
    motivation: "Apprendre la patience par le corps.",
    category: "sport",
    color: "gold",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 5,
    estimatedCost: 3200,
    savedAmount: 0,
    estimatedHours: 260,
    monthsFromNow: 28,
    country: "Chine",
    city: "Dengfeng",
    minAge: 18,
    dependsOn: ["camp-boxe-thai-thailande"],
    steps: [
      { title: "Repérer les académies ouvertes aux étrangers" },
      { title: "Apprendre 50 mots de mandarin de survie", estimatedMinutes: 30 },
      { title: "Budget : 3 200 € à épargner", priority: "HIGH" },
      { title: "Demander le visa L", dueInDays: 780 },
    ],
    checklist: ["Certificat médical", "Tenue d'entraînement", "Adaptateur secteur"],
  },
  {
    slug: "jouer-dans-un-film",
    title: "Jouer dans un film",
    emoji: "🎬",
    description:
      "Décrocher un vrai rôle — même une silhouette parlante — dans un long-métrage ou une série diffusée.",
    motivation: "Voir mon nom défiler au générique au moins une fois dans ma vie.",
    category: "creativite",
    color: "peach",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    difficulty: 4,
    estimatedCost: 600,
    savedAmount: 300,
    estimatedHours: 180,
    monthsFromNow: 20,
    country: "France",
    steps: [
      {
        title: "Se rendre visible",
        children: [
          { title: "Book photo professionnel", done: true },
          { title: "Bande démo de 90 secondes", done: false },
          { title: "S'inscrire sur 3 plateformes de casting", done: true },
        ],
      },
      { title: "Prendre 10 cours de théâtre", estimatedMinutes: 120 },
      { title: "Passer 20 castings figuration", priority: "HIGH" },
      { title: "Relancer les directeurs de casting rencontrés" },
    ],
    checklist: ["CV artistique à jour", "Photos noir & blanc", "Monologue de 2 min prêt"],
  },
  {
    slug: "bac-avec-mention",
    title: "Avoir le bac avec mention",
    emoji: "🎓",
    description: "Décrocher le baccalauréat avec au minimum la mention Bien.",
    motivation: "C'est la clé qui ouvre presque tout le reste de cette liste.",
    category: "etudes",
    color: "lilac",
    status: "DONE",
    priority: "CRITICAL",
    difficulty: 3,
    estimatedCost: 0,
    estimatedHours: 400,
    monthsFromNow: -30,
    country: "France",
    steps: [
      { title: "Réviser les spécialités", done: true },
      { title: "Passer les épreuves anticipées", done: true },
      { title: "Grand oral", done: true },
      { title: "Résultats : mention Bien", done: true },
    ],
  },
  {
    slug: "avoir-un-vespa",
    title: "Avoir un Vespa",
    emoji: "🛵",
    description: "Un Vespa d'occasion en bon état, couleur pastel, pour la liberté au quotidien.",
    motivation: "La liberté de partir n'importe où sans demander à personne.",
    category: "style-de-vie",
    color: "aqua",
    status: "IN_PROGRESS",
    priority: "HIGH",
    difficulty: 2,
    estimatedCost: 2400,
    savedAmount: 1600,
    estimatedHours: 40,
    monthsFromNow: 7,
    country: "France",
    minAge: 18,
    steps: [
      { title: "Obtenir le permis A1/B", done: true },
      { title: "Épargner 2 400 €", priority: "HIGH" },
      { title: "Surveiller les annonces d'occasion", estimatedMinutes: 20 },
      { title: "Faire contrôler la mécanique avant achat", priority: "CRITICAL" },
      { title: "Assurance et équipement" },
    ],
    checklist: ["Casque homologué", "Antivol U", "Gants", "Devis assurance"],
  },
  {
    slug: "saut-a-l-elastique",
    title: "Saut à l'élastique",
    emoji: "🪢",
    description: "Sauter du viaduc de la Souleuvre, 61 mètres de vide.",
    motivation: "Prouver que la peur ne décide pas à ma place.",
    category: "aventure",
    color: "mint",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 2,
    estimatedCost: 130,
    savedAmount: 60,
    estimatedHours: 8,
    monthsFromNow: 5,
    country: "France",
    city: "Normandie",
    minAge: 18,
    steps: [
      { title: "Choisir le site et la date", priority: "HIGH" },
      { title: "Réserver le créneau" },
      { title: "Trouver quelqu'un pour filmer" },
    ],
    checklist: ["Certificat médical", "Vêtements près du corps"],
  },
  {
    slug: "preparation-shooting-photo",
    title: "Préparation + shooting photo",
    emoji: "📸",
    description:
      "Un vrai shooting artistique : préparation physique, styliste, maquillage, photographe professionnel.",
    motivation: "Garder une trace de qui j'étais à cet âge exactement.",
    category: "creativite",
    color: "blush",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    difficulty: 2,
    estimatedCost: 550,
    savedAmount: 400,
    estimatedHours: 60,
    monthsFromNow: 4,
    country: "France",
    steps: [
      { title: "Créer le moodboard", done: true },
      { title: "Préparation physique 8 semaines", done: false, estimatedMinutes: 45 },
      { title: "Trouver le photographe", done: true },
      { title: "Choisir les tenues", done: false },
      { title: "Réserver le studio" },
    ],
    checklist: ["Moodboard Pinterest", "3 tenues", "Rendez-vous coiffure la veille"],
  },
  {
    slug: "voyage-avec-papi-et-mami",
    title: "Voyage avec Papi et Mami",
    emoji: "💛",
    description:
      "Emmener mes grands-parents une semaine là où ils rêvent d'aller depuis toujours — et tout payer moi-même.",
    motivation: "Le temps avec eux est la seule chose de cette liste qui ne se rattrape pas.",
    category: "famille-amis",
    color: "gold",
    status: "TODO",
    priority: "CRITICAL",
    difficulty: 3,
    estimatedCost: 2200,
    savedAmount: 700,
    estimatedHours: 50,
    monthsFromNow: 10,
    country: "Italie",
    people: ["Papi", "Mami"],
    isFavorit: true,
    steps: [
      { title: "Leur demander où ils veulent aller", priority: "CRITICAL", done: true },
      { title: "Trouver un hébergement accessible" },
      { title: "Épargner 2 200 €", priority: "HIGH" },
      { title: "Organiser un rythme adapté (pas plus de 2 visites/jour)" },
      { title: "Prévoir les traitements médicaux" },
    ],
    checklist: ["Cartes vitales et mutuelles", "Assurance annulation", "Photos imprimées au retour"],
  },
  {
    slug: "saut-en-parachute",
    title: "Saut en parachute",
    emoji: "🪂",
    description: "Saut en tandem à 4 000 m, avec vidéo.",
    motivation: "Après l'élastique, passer au niveau au-dessus.",
    category: "aventure",
    color: "aqua",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 2,
    estimatedCost: 320,
    savedAmount: 0,
    estimatedHours: 10,
    monthsFromNow: 9,
    country: "France",
    minAge: 18,
    dependsOn: ["saut-a-l-elastique"],
    steps: [
      { title: "Réserver un tandem" },
      { title: "Option vidéo" },
      { title: "Vérifier la météo la veille" },
    ],
  },
  {
    slug: "road-trip-entre-amis",
    title: "Road trip entre amis",
    emoji: "🚐",
    description: "Deux semaines de van sur la côte, sans itinéraire figé.",
    motivation: "Les meilleurs souvenirs ne se planifient pas — mais le van, si.",
    category: "voyage",
    color: "peach",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 2,
    estimatedCost: 900,
    savedAmount: 250,
    estimatedHours: 80,
    monthsFromNow: 12,
    country: "Portugal",
    people: ["Aboud"],
    steps: [
      { title: "Fixer les dates avec le groupe", priority: "HIGH" },
      { title: "Réserver le van" },
      { title: "Répartir le budget essence / nourriture" },
      { title: "Playlist collaborative" },
    ],
    checklist: ["Permis depuis + de 3 ans", "Carte verte", "Glacière", "Appareil photo argentique"],
  },
  {
    slug: "lieux-tournage-prison-break",
    title: "Lieux de tournage Prison Break",
    emoji: "🔓",
    description:
      "Visiter la prison de Joliet dans l'Illinois et les autres lieux emblématiques de la série.",
    motivation: "Marcher dans le décor d'une histoire qui m'a marquée.",
    category: "voyage",
    color: "lilac",
    status: "TODO",
    priority: "LOW",
    difficulty: 3,
    estimatedCost: 1800,
    savedAmount: 0,
    estimatedHours: 60,
    monthsFromNow: 24,
    country: "États-Unis",
    city: "Chicago",
    steps: [
      { title: "Lister les lieux encore visitables" },
      { title: "Demander l'ESTA", dueInDays: 660 },
      { title: "Épargner 1 800 €" },
      { title: "Réserver la visite guidée de Joliet" },
    ],
  },
  {
    slug: "parler-allemand-couramment",
    title: "Parler allemand couramment",
    emoji: "🇩🇪",
    description: "Atteindre un niveau B2/C1 : tenir une conversation d'une heure sans basculer en anglais.",
    motivation: "Une langue de plus, c'est une vie de plus.",
    category: "etudes",
    color: "lilac",
    status: "IN_PROGRESS",
    priority: "HIGH",
    difficulty: 4,
    estimatedCost: 400,
    savedAmount: 400,
    estimatedHours: 600,
    monthsFromNow: 30,
    country: "Allemagne",
    steps: [
      { title: "Passer de A2 à B1", done: true, estimatedMinutes: 30 },
      {
        title: "Routine quotidienne",
        children: [
          { title: "15 min d'application chaque matin", done: true },
          { title: "1 série en VO par semaine", done: false },
          { title: "1 échange linguistique par semaine", done: false },
        ],
      },
      { title: "Passer l'examen Goethe B2", dueInDays: 800, priority: "HIGH" },
      { title: "Séjour d'immersion de 2 semaines" },
    ],
  },
  {
    slug: "wolf-cut",
    title: "Wolf Cut",
    emoji: "💇‍♀️",
    description: "Oser la coupe wolf cut chez un coiffeur qui sait vraiment la faire.",
    motivation: "Changer de tête pour changer d'époque.",
    category: "style-de-vie",
    color: "blush",
    status: "TODO",
    priority: "LOW",
    difficulty: 1,
    estimatedCost: 80,
    savedAmount: 80,
    estimatedHours: 3,
    monthsFromNow: 2,
    country: "France",
    steps: [
      { title: "Trouver un salon spécialisé" },
      { title: "Réserver" },
      { title: "Photo avant / après" },
    ],
  },
  {
    slug: "interviewer-jul",
    title: "Interviewer JUL",
    emoji: "🎤",
    description: "Obtenir et mener une vraie interview avec JUL, préparée sérieusement.",
    motivation: "Poser les questions que personne ne lui pose jamais.",
    category: "creativite",
    color: "gold",
    status: "WAITING",
    priority: "MEDIUM",
    difficulty: 5,
    estimatedCost: 200,
    savedAmount: 200,
    estimatedHours: 90,
    monthsFromNow: 26,
    country: "France",
    city: "Marseille",
    people: ["JUL"],
    steps: [
      { title: "Créer un média (podcast ou chaîne) crédible", priority: "HIGH" },
      { title: "Publier 10 épisodes réguliers" },
      { title: "Identifier son attaché de presse" },
      { title: "Envoyer un dossier de demande" },
      { title: "Préparer 20 questions inédites" },
    ],
    checklist: ["Micro correct", "Questions écrites", "Autorisation d'enregistrer"],
  },
  {
    slug: "safari",
    title: "Safari",
    emoji: "🦁",
    description: "Un safari de 6 jours dans le Masai Mara, en saison sèche.",
    motivation: "Voir des animaux libres, pas en cage.",
    category: "voyage",
    color: "gold",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 3,
    estimatedCost: 2600,
    savedAmount: 150,
    estimatedHours: 40,
    monthsFromNow: 22,
    country: "Kenya",
    steps: [
      { title: "Choisir une agence éthique" },
      { title: "Vaccins fièvre jaune + traitement antipaludique", dueInDays: 600 },
      { title: "Épargner 2 600 €", priority: "HIGH" },
      { title: "Louer un téléobjectif" },
    ],
    checklist: ["Passeport", "Vaccin fièvre jaune", "Jumelles", "Vêtements neutres"],
  },
  {
    slug: "service-militaire",
    title: "Service militaire",
    emoji: "🎖️",
    description: "Effectuer un engagement volontaire, aller au bout de la formation initiale.",
    motivation: "Me confronter à un cadre plus dur que tout ce que je connais.",
    category: "carriere",
    color: "mint",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 5,
    estimatedCost: 0,
    estimatedHours: 1200,
    monthsFromNow: 18,
    country: "France",
    minAge: 18,
    steps: [
      { title: "Rendez-vous au CIRFA" },
      { title: "Tests physiques et psychotechniques", priority: "HIGH" },
      { title: "Préparation physique 6 mois", estimatedMinutes: 90 },
      { title: "Dossier médical" },
    ],
  },
  {
    slug: "equipe-de-boxe-algerie",
    title: "Intégrer l'équipe de boxe d'Algérie",
    emoji: "🇩🇿",
    description:
      "Être sélectionnée en équipe nationale algérienne de boxe : licence, compétitions qualificatives, sélection.",
    motivation: "Représenter le pays de ma famille, sur un ring, avec mon nom sur le dos.",
    category: "sport",
    color: "blush",
    status: "BLOCKED",
    priority: "HIGH",
    difficulty: 5,
    estimatedCost: 1500,
    savedAmount: 100,
    estimatedHours: 1500,
    monthsFromNow: 30,
    country: "Algérie",
    dependsOn: ["camp-boxe-thai-thailande"],
    steps: [
      { title: "Obtenir la licence de la fédération algérienne", priority: "CRITICAL" },
      { title: "Régulariser les papiers de nationalité" },
      {
        title: "Compétitions qualificatives",
        children: [
          { title: "10 combats amateurs en France" },
          { title: "Participer à un tournoi national en Algérie" },
        ],
      },
      { title: "Entraînement 6 jours/semaine", estimatedMinutes: 120 },
    ],
  },
  {
    slug: "un-an-a-l-etranger-seule",
    title: "Partir un an à l'étranger seule",
    emoji: "🌍",
    description:
      "Vivre douze mois complets dans un autre pays : logement, travail ou études, vie sociale — tout à construire.",
    motivation: "Savoir que je peux recommencer ma vie à zéro n'importe où.",
    category: "voyage",
    color: "aqua",
    status: "TODO",
    priority: "HIGH",
    difficulty: 5,
    estimatedCost: 9000,
    savedAmount: 500,
    estimatedHours: 2000,
    monthsFromNow: 30,
    country: "Allemagne",
    minAge: 18,
    dependsOn: ["bac-avec-mention", "parler-allemand-couramment"],
    isFavorit: true,
    steps: [
      { title: "Choisir le pays et la ville", priority: "HIGH" },
      { title: "Choisir la formule : études, PVT, ou travail" },
      { title: "Constituer 9 000 € de matelas financier", priority: "CRITICAL" },
      { title: "Trouver un logement sur place" },
      { title: "Gérer l'administratif (visa, sécurité sociale, banque)" },
      { title: "Prévenir la famille et organiser les retours" },
    ],
    checklist: ["Passeport", "Traduction assermentée des diplômes", "Compte bancaire local", "Assurance santé"],
  },
  {
    slug: "urbex-avec-aboud",
    title: "Faire un vrai urbex avec Aboud",
    emoji: "🏚️",
    description:
      "Explorer un lieu abandonné majeur — sanatorium ou usine — avec préparation, matériel et photos argentiques.",
    motivation: "Les endroits que le monde a oubliés ont les meilleures histoires.",
    category: "aventure",
    color: "lilac",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 3,
    estimatedCost: 150,
    savedAmount: 150,
    estimatedHours: 25,
    monthsFromNow: 6,
    country: "France",
    people: ["Aboud"],
    notes:
      "Ne jamais y aller seul·e, vérifier le statut légal du lieu et prévenir quelqu'un de l'itinéraire.",
    steps: [
      { title: "Repérer 3 lieux accessibles légalement", priority: "HIGH" },
      { title: "Vérifier la sécurité (amiante, plancher, accès)", priority: "CRITICAL" },
      { title: "Préparer le matériel" },
      { title: "Fixer la date avec Aboud" },
    ],
    checklist: ["Lampe frontale", "Masque FFP2", "Chaussures montantes", "Batterie externe", "Prévenir un proche"],
  },
  {
    slug: "toulouse-marseille-a-velo",
    title: "Toulouse → Marseille à vélo avec Aboud",
    emoji: "🚴‍♀️",
    description: "Environ 500 km par le canal du Midi puis la côte, en 6 jours, en autonomie.",
    motivation: "Traverser une région à la force des jambes change la façon de la regarder.",
    category: "aventure",
    color: "mint",
    status: "TODO",
    priority: "MEDIUM",
    difficulty: 4,
    estimatedCost: 450,
    savedAmount: 120,
    estimatedHours: 120,
    monthsFromNow: 11,
    country: "France",
    people: ["Aboud"],
    steps: [
      {
        title: "Préparation physique",
        children: [
          { title: "Sortie de 40 km", done: true },
          { title: "Sortie de 80 km" },
          { title: "Deux jours consécutifs de 70 km" },
        ],
      },
      { title: "Réviser le vélo et les sacoches", priority: "HIGH" },
      { title: "Tracer l'itinéraire jour par jour" },
      { title: "Réserver les étapes" },
    ],
    checklist: ["Kit de réparation", "Sacoches étanches", "GPS ou traces GPX", "Crème solaire"],
  },
  {
    slug: "twingo-personnalisee-jul",
    title: "Avoir une Twingo personnalisée JUL",
    emoji: "🚗",
    description: "Une Twingo d'occasion, covering et intérieur customisés aux couleurs de l'univers JUL.",
    motivation: "Une voiture qui me ressemble à 100 %, même si personne ne comprend.",
    category: "style-de-vie",
    color: "peach",
    status: "TODO",
    priority: "LOW",
    difficulty: 3,
    estimatedCost: 5500,
    savedAmount: 0,
    estimatedHours: 70,
    monthsFromNow: 27,
    country: "France",
    minAge: 18,
    steps: [
      { title: "Passer le permis B", priority: "CRITICAL" },
      { title: "Trouver une Twingo fiable" },
      { title: "Devis covering personnalisé" },
      { title: "Vérifier la légalité des modifications" },
    ],
  },
  {
    slug: "etre-prof-de-maths",
    title: "Être prof de maths",
    emoji: "➗",
    description: "Décrocher le concours et enseigner les mathématiques dans le secondaire.",
    motivation: "Rendre à d'autres ce qu'un prof m'a donné.",
    category: "carriere",
    color: "lilac",
    status: "IN_PROGRESS",
    priority: "CRITICAL",
    difficulty: 5,
    estimatedCost: 3000,
    savedAmount: 800,
    estimatedHours: 3000,
    monthsFromNow: 32,
    country: "France",
    dependsOn: ["bac-avec-mention"],
    steps: [
      { title: "Licence de mathématiques", done: false, priority: "CRITICAL" },
      {
        title: "Valider les années",
        children: [
          { title: "L1 validée", done: true },
          { title: "L2 validée", done: true },
          { title: "L3 en cours" },
        ],
      },
      { title: "Master MEEF" },
      { title: "Préparer le CAPES" },
      { title: "Faire des stages d'observation en collège" },
    ],
  },
  {
    slug: "jeu-televise",
    title: "Participer à un jeu télévisé",
    emoji: "📺",
    description: "Être candidate dans une émission de jeu et passer à l'antenne.",
    motivation: "Pour la tête de la famille devant la télé.",
    category: "creativite",
    color: "aqua",
    status: "TODO",
    priority: "LOW",
    difficulty: 3,
    estimatedCost: 100,
    savedAmount: 100,
    estimatedHours: 40,
    monthsFromNow: 14,
    country: "France",
    steps: [
      { title: "Lister les émissions qui recrutent" },
      { title: "Envoyer 5 candidatures" },
      { title: "Préparer le casting téléphonique" },
      { title: "Réviser la culture générale", estimatedMinutes: 30 },
    ],
  },
  {
    slug: "deuxieme-prenom-fraise",
    title: "Ajouter officiellement « Fraise » comme deuxième prénom",
    emoji: "🍓",
    description:
      "Déposer une demande de changement de prénom en mairie pour ajouter « Fraise » à l'état civil.",
    motivation: "Une blague devenue une identité — autant l'assumer sur les papiers.",
    category: "style-de-vie",
    color: "blush",
    status: "TODO",
    priority: "LOW",
    difficulty: 2,
    estimatedCost: 60,
    savedAmount: 60,
    estimatedHours: 15,
    monthsFromNow: 15,
    country: "France",
    minAge: 18,
    notes:
      "Procédure gratuite en mairie de résidence ou de naissance ; il faut un intérêt légitime et un dossier justificatif.",
    steps: [
      { title: "Se renseigner auprès de la mairie", priority: "HIGH" },
      { title: "Réunir les justificatifs d'usage du prénom" },
      { title: "Déposer le dossier" },
      { title: "Mettre à jour les papiers après acceptation" },
    ],
    checklist: ["Acte de naissance", "Justificatif de domicile", "Pièce d'identité", "Lettre de motivation"],
  },
  {
    slug: "privatiser-un-parc-d-attractions",
    title: "Privatiser un parc d'attractions",
    emoji: "🎡",
    description:
      "L'objectif final : privatiser un parc d'attractions une soirée entière, et y inviter tous ceux qui comptent. Aucune file d'attente, aucune limite, juste nous.",
    motivation:
      "Si j'arrive à faire ça, c'est que j'aurai réussi tout le reste. C'est la ligne d'arrivée.",
    category: "aventure",
    color: "gold",
    status: "TODO",
    priority: "CRITICAL",
    difficulty: 5,
    estimatedCost: 25000,
    savedAmount: 300,
    estimatedHours: 400,
    monthsFromNow: 34,
    country: "France",
    isFinal: true,
    isFavorit: true,
    dependsOn: ["etre-prof-de-maths", "un-an-a-l-etranger-seule"],
    steps: [
      { title: "Identifier les parcs qui acceptent les privatisations", priority: "HIGH" },
      { title: "Demander 5 devis officiels" },
      {
        title: "Construire le financement",
        children: [
          { title: "Épargne personnelle sur 3 ans" },
          { title: "Participation des invités" },
          { title: "Recherche de partenaires ou sponsors" },
        ],
      },
      { title: "Fixer la date et la liste d'invités", priority: "CRITICAL" },
      { title: "Organiser la logistique (transport, repas, photographe)" },
      { title: "Vivre la soirée sans regarder son téléphone" },
    ],
    checklist: [
      "Devis signés",
      "Assurance événement",
      "Liste d'invités définitive",
      "Playlist de la soirée",
      "Photographe réservé",
    ],
  },
];
